server:
    port: 8090
    servlet:
        context-path: /seckill

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.p6spy.engine.spy.P6SpyDriver
            url: jdbc:p6spy:mysql://127.0.0.1:3306/seckill?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
            username: root
            password: root
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
    redis:
        timeout: 10000ms
        host: 127.0.0.1
        port: 6379
        password:
        lettuce:
            pool:
                #最大连接数，默认8
                max-active: 1024
                #最大连接阻塞等待时间，默认-1
                max-wait: 10000ms
                #最大空闲连接
                max-idle: 200
                #最小空闲连接
                min-idle: 5
    rabbitmq:
        #服务器
        host: 127.0.0.1
        #用户名
        username: guest
        #密码
        password: guest
        #虚拟主机
        virtual-host: /
        #端口
        port: 5672
        listener:
            simple:
                #消费者最小数量
                concurrency: 10
                #消费者最大数量
                max-concurrency: 10
                #限制消费者每次只能处理一条消息，处理完在继续下一条消息
                prefetch: 1
                #启动是默认启动容器
                auto-startup: true
                #被拒绝时重新进入队列
                default-requeue-rejected: true
        template:
            retry:
                #发布重试，默认false
                enabled: true
                #重试时间，默认1000ms
                initial-interval: 1000ms
                #重试最大次数，默认3次
                max-attempts: 3
                #最大重试间隔时间
                max-interval: 10000ms
                #重试的间隔乘数，比如配2。0  第一等10s 第二次等20s 第三次等40s
                multiplier: 1
    web:
        resources:
            static-locations: classpath:/static/
    thymeleaf:
        cache: false

mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    global-config:
        db-config:
            logic-not-delete-value: 0
            logic-delete-value: 1
            logic-delete-field: dflag
        banner: false
    configuration:
        map-underscore-to-camel-case: true